services:
  recbole-env:
    image: recbole-env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recbole-env
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]